name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
    - name: Run docker
      run: docker run --name main-server -p 8088:80 -v ${{env.GITHUB_WORKSPACE}}/:/usr/share/nginx/html:ro -d nginx
